// Generated by scripts/danger-calibrate.ts (300 training matches at Master). Do not edit by hand.
// Feature order: READY_FEATURES, WAIT_FEATURES and FAN_FEATURES in ./danger.ts
export const MODEL = {
  "ready": {
    "bias": -4.9916,
    "w": [
      1.1705,
      0.2377,
      0.806,
      4.5792,
      4.2639,
      -1.4945,
      0.9929,
      -2.1413,
      1.074,
      -0.2528,
      0.2809,
      0.6089,
      0.3119,
      -0.2074
    ]
  },
  "wait": {
    "bias": -4.3803,
    "w": [
      -1.6058,
      -2.2348,
      0.3549,
      0.925,
      1.3673,
      1.1935,
      1.048,
      2.7607,
      3.3613,
      0.6152,
      0.8136,
      1.081,
      1.3308,
      -1.8585,
      -6.1965,
      -0.358,
      -0.1249,
      -0.544,
      0.0203,
      0.1756,
      0.0206,
      0.3591,
      1.2072,
      0.1476,
      0.5875,
      -0.3738
    ]
  },
  "fan": {
    "bias": 1.0691,
    "w": [
      0.4511,
      1.2809,
      -0.8028,
      1.9027,
      0.0276,
      0.0971
    ]
  },
  "levels": {
    "medium": 0.03,
    "danger": 0.08
  }
};
