// Generated by scripts/danger-calibrate.ts (300 training matches at Master). Do not edit by hand.
// Feature order: READY_FEATURES, WAIT_FEATURES and FAN_FEATURES in ./danger.ts
export const MODEL = {
  "ready": {
    "bias": -5.0098,
    "w": [
      1.2276,
      0.1427,
      0.7206,
      2.4936,
      3.6361,
      -1.4369,
      1.0586,
      -1.9709,
      1.0871,
      -0.3291,
      0.3787,
      0.5311,
      0.4746,
      0.8286
    ]
  },
  "wait": {
    "bias": -4.3576,
    "w": [
      -1.5029,
      -2.1171,
      0.3251,
      0.8372,
      1.3439,
      1.1137,
      1.2294,
      2.6389,
      3.3079,
      0.4606,
      0.763,
      1.0543,
      1.3421,
      -1.88,
      -6.1213,
      -0.4083,
      -0.0653,
      -0.4467,
      0.0293,
      0.2114,
      0.0179,
      0.3982,
      1.0308,
      0.1826,
      0.6042,
      -0.3137
    ]
  },
  "fan": {
    "bias": 1.0024,
    "w": [
      0.4086,
      1.1959,
      -0.6841,
      1.7915,
      0.0718,
      0.2122
    ]
  },
  "levels": {
    "medium": 0.03,
    "danger": 0.08
  }
};
